# Generated by Django 5.0.14 on 2026-09-14 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0, verbose_name='XP total')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Gamificação',
                'verbose_name_plural': 'Perfis de Gamificação',
                'ordering': ['-xp_total'],
            },
        ),
        migrations.CreateModel(
            name='RegistroXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_concedido', models.PositiveIntegerField(default=10, verbose_name='XP concedido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_xp', to=settings.AUTH_USER_MODEL)),
                ('resolucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_xp', to='tarefas.resolucaotarefa')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_xp', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Registro de XP',
                'verbose_name_plural': 'Registros de XP',
            },
        ),
        migrations.AddConstraint(
            model_name='registroxp',
            constraint=models.UniqueConstraint(fields=('aluno', 'tarefa'), name='um_registro_xp_por_aluno_e_tarefa'),
        ),
    ]
