# Generated by Django 5.0.14 on 2026-09-04 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radiografias', '0002_alter_casoclinico_professor'),
        ('turmas', '0003_turma_alunos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrucoes', models.TextField(verbose_name='Instruções da Tarefa')),
                ('coordenadas_gabarito', models.JSONField(verbose_name='Gabarito (Bounding Box)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caso_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='radiografias.casoclinico')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ResolucaoTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordenadas_submetidas', models.JSONField()),
                ('acertou', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_resolucoes', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucoes', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Resolução de Tarefa',
                'verbose_name_plural': 'Resoluções de Tarefas',
            },
        ),
    ]
