# Generated by Django 5.0.14 on 2026-08-17 19:07

import academico.models.turma
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Turma')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo_convite', models.CharField(default=academico.models.turma.gerar_codigo_convite, max_length=10, unique=True, verbose_name='Código de Convite')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Turma Ativa')),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'perfil': 'aluno'}, related_name='turmas_matriculadas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos Matriculados')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
