# Generated by Django 5.0.14 on 2026-09-02 20:20

import django.db.models.deletion
import turmas.models.turma
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('invite_code', models.CharField(default=turmas.models.turma.gerar_codigo_convite, editable=False, max_length=6, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
