# Generated by Django 5.0.14 on 2026-09-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='invite_code',
            new_name='codigo_convite',
        ),
    ]
