# Generated by Django 5.0.14 on 2026-09-02 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_rename_invite_code_turma_codigo_convite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas_com_aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
