# Generated by Django 5.0.14 on 2026-08-12 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Caso Clínico')),
                ('descricao', models.TextField(help_text='Diretriz clínica ou descrição do que o aluno deve analisar.', verbose_name='Descrição / Observações')),
                ('regiao_anatomica', models.CharField(choices=[('maxila', 'Maxila'), ('mandibula', 'Mandíbula'), ('atm', 'Articulação Temporomandibular (ATM)'), ('dentes', 'Dentes Específicos'), ('geral', 'Panorâmica Geral')], default='geral', max_length=50, verbose_name='Região Anatômica')),
                ('imagem', models.ImageField(upload_to='radiografias/%Y/%m/', verbose_name='Arquivo de Imagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='casos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Caso Clínico',
                'verbose_name_plural': 'Casos Clínicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
