# Generated by Django 5.0.14 on 2026-09-09 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiografias', '0002_alter_casoclinico_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoclinico',
            name='modelo_3d',
            field=models.FileField(blank=True, null=True, upload_to='modelos_3d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'])]),
        ),
    ]
