# Generated by Django 5.0.14 on 2026-09-22 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiografias', '0003_casoclinico_modelo_3d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoRadiografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('consulta', 'Consulta'), ('inclusao', 'Inclusao'), ('exclusao', 'Exclusao')], max_length=12)),
                ('origem', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('radiografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_auditados', to='radiografias.casoclinico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['radiografia', 'criado_em'], name='radiografia_radiogr_4fc2b7_idx')],
            },
        ),
    ]
