# Generated by Django 5.0.14 on 2026-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tokenderecuperacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chave_secreta_2fa',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Chave Secreta 2FA'),
        ),
    ]
