# Generated by Django 5.0.14 on 2026-09-22 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='chave_secreta_2fa',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Chave Secreta 2FA'),
        ),
        migrations.CreateModel(
            name='SolicitacaoDireitoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acesso', 'Acesso aos dados'), ('correcao', 'Correcao de dados'), ('exclusao', 'Exclusao de dados'), ('restricao', 'Restricao de tratamento'), ('revogacao', 'Revogacao de consentimento')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_atendimento', 'Em atendimento'), ('concluida', 'Concluida'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_termos', models.CharField(max_length=20)),
                ('versao_privacidade', models.CharField(max_length=20)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aceito_em'],
                'indexes': [models.Index(fields=['usuario', 'aceito_em'], name='users_conse_usuario_9a8954_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_informado', models.EmailField(blank=True, max_length=254)),
                ('evento', models.CharField(choices=[('login_sucesso', 'Login realizado'), ('login_falhou', 'Login negado'), ('login_2fa_pendente', 'Aguardando 2FA'), ('login_2fa_falhou', '2FA negado'), ('logout', 'Logout realizado'), ('acesso_radiografia', 'Acesso a radiografia'), ('alteracao_critica', 'Alteracao critica'), ('exportacao_dados', 'Exportacao de dados'), ('solicitacao_direito', 'Solicitacao de direito do titular')], max_length=32)),
                ('recurso', models.CharField(blank=True, max_length=120)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'criado_em'], name='users_logac_usuario_b17421_idx'), models.Index(fields=['evento', 'criado_em'], name='users_logac_evento_e9dca8_idx')],
            },
        ),
    ]
